version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"  
    depends_on:
      - mysql  
     

  mysql:  
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb